### ISSUE TITLE
[FEATURE] - Refactor "Design Brief" to Some New Name

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#31]
Find a new name for the design brief that makes sense both internally (not redundant) and externally (not misleading).

### Context
"Man we need better naming convention. @narvcharv Maybe we should restructure the Design Brief to more of an RFP? What's the difference?"

_Originally posted by @JLefebvre55 in https://github.com/UTAgritech/PeaPod/issues/30#issuecomment-855470291_

**Comment by narvcharv** [comment]
What about:

Design Brief --> Requirements
Design Proposal --> Solution Overview
`New` SFD
`Eventually` Report (DSFC Submission)
