### ISSUE TITLE
[FEATURE] - Solution Overview Draft

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#52]
> Assigned to @JLefebvre55, @nchareunsouk, due by **July 3rd**

### **NOTE**: PR has been linked. Work is to be done on the `docs-solutionoverview` branch.

**Here**: [`/docs/design/solutionoverview`](https://github.com/UTAgritech/PeaPod/tree/docs-solutionoverview/docs/design/solutionoverview)

**Scope**: Detail the **purpose**, **function** (inputs/outputs, system vs. surroundings, assumptions), and **method** (process steps/tree) of the system. If the method is multi-step (aka relies on a multi-part system), recurse (**features**) and inherit.
- [x] Detail _overall_ solution
- [x] Detail subsystems:
  - [x] Automation - @JLefebvre55 
  - [x] Housing - @JLefebvre55 
  - [x] Aeroponics - @nchareunsouk 
  - [x] Environment Control
    - [x] Air Temperature - @nchareunsouk 
    - [x] Air Humidification - @JLefebvre55 
    - [x] Air Dehumidification - @nchareunsouk 
    - [x] Solution Temperature - ~~@nchareunsouk~~ @JLefebvre55 
    - [x] Solution Nutrients - @nchareunsouk 
    - [x] Solution pH - @nchareunsouk 
    - [x] Lighting - @JLefebvre55 
  - [x] Optimization - @JLefebvre55

**Comment by JLefebvre55** [comment]
@nchareunsouk Created draft PR. Work is to be done on `docs-solutionoverview`

**Comment by JLefebvre55** [comment]
@nchareunsouk Might want to combine the nutrient solution ones into a single section, cause we're using a reservoir.

**Comment by nchareunsouk** [comment]
I found a way to have precise dosing through automation with an inline injection method. Uses off the shelf components.

**Comment by nchareunsouk** [comment]
Do we need to manage solution temperature?

**Comment by JLefebvre55** [comment]
> Do we need to manage solution temperature?

Good question @nchareunsouk. I think so, considering that we're also trying to control air temperature, and water has a high thermal capacity.

I'm thinking since we're doing inline nutrient/pH injection AND having a tank, we should consider either a) an **inline** temp. sensor + water block + peltier PID system (like how pop machines do their cooling) or b) pre-heating/-cooling the reservoir (temp. sensor + water block + peltier PID)

**Comment by nchareunsouk** [comment]
> I'm thinking since we're doing inline nutrient/pH injection AND having a tank, we should consider either a) an **inline** temp. sensor + water block + peltier PID system (like how pop machines do their cooling) or b) pre-heating/-cooling the reservoir (temp. sensor + water block + peltier PID)

@JLefebvre55. Outdoor misting systems drop the temperature of the air by a significant amount which means they draw heat from the air. So an inline pre-cooler (using peltier) would be ok, that way no control loop would be needed.

Assuming you meant the tank in "pre-heating/-cooling the reservoir", cooling the tank may be challenging due to the insulative properties of the tank however it would help to maintain a more consistent temperature if an inline pre-cooler was  installed before it.

**Comment by nchareunsouk** [comment]
> Assuming you meant the tank in "pre-heating/-cooling the reservoir", cooling the tank may be challenging due to the insulative properties of the tank however it would help to maintain a more consistent temperature if an inline pre-cooler was installed before it.

@JLefebvre55. Unless you meant the reservoir where the initial water is stored, in which case there are a few solutions to accomplish that.

**Comment by JLefebvre55** [comment]
Took over water temperature section
