### ISSUE TITLE
[DOCS] - Design Report Section: Adherence to Constraints

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#53]
> To be developed on a branch named `docs-designreport-constraints`

Show consideration and details; Include the following (_300 chars each_):
  - [x] Volume/Dimensions - @JonasMarshall 
  - [x] Power - @JLefebvre55 
  - [x] Water - @JLefebvre55 
  - [x] Mass - @JonasMarshall
  - [x] Data Connection - @JLefebvre55  
  - [x] Crew Time - @narvcharv 
  - [x] Operational Constraints - @narvcharv 
  - [x] Extra? constraints Requirements doc inheriting from `[2]`, as well as R1d, R4, R5? - @narvcharv

**Comment by JLefebvre55** [comment]
Linked a draft pull request to track completion.

**Comment by narvcharv** [comment]
On [2]:

- Included M2
- Included M33 by overlap
- Included M48 by overlap with Process Reliability
- Included M49 by overlap with Process Reliability
- Included M52, M53 by overlap with 2.3.1
- M54 addressed above (awaiting details)


On Requirements:

- Added R1d
- Added R4
- Included R5 by overlap with Operational Constraints

**Comment by JLefebvre55** [comment]
@nchareunsouk Can you review this section today/tomorrow? I.e. solid read-through for completeness (don't worry about length). I'll finish up #64

**Comment by JLefebvre55** [comment]
@nchareunsouk Review needed on my sections
