### ISSUE TITLE
[FEATURE] - Design pump water supply

### ISSUE THREAD

**Issue by nchareunsouk** [OpenFormTech/PeaPod#71]
Design a system that feeds water into the pump.

**Due Date: TBD**

### Context
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- [ ] Needs to attach to the pump input (3/8)
- [ ] Needs to be filtered (distilled)
- [ ] Needs to meet the flow rate of the output

**Describe alternatives you've considered**
- [ ] Bucket with clean water

**Comment by JLefebvre55** [comment]
@nchareunsouk I think we can just leave this as an assumed input, and for testing just use hose water with a filter.

Also - not sure the "forwards pressure bypassing the diaphragm" thing is really a _problem_ per say - it means we don't have to prime the system, and the nozzle solenoid will stop the water from going all the way through.

Maybe mark this as closed?

**Comment by JLefebvre55** [comment]
Part of #25
