### ISSUE TITLE
[FEATURE] - Design Report: Crew Time Performance Constraint (2.3.6/2.3.9)

### ISSUE THREAD

**Issue by nchareunsouk** [OpenFormTech/PeaPod#76]
**Add manual pollination as a potential crew time requirement.**
Most vegetables (roots) such as potatoes and carrots may not require pollination but fruits such as strawberries do. 
Also, some plants like cucumbers are self-pollinating.
Manual pollination would most likely require swabbing each plant (only during the pollination period).

_Note: Periodic turbo blower fans may be a way to automate pollination._

**Output processing**
Provide 2-3 examples of different kinds of output processing with time requirements

**Output storage**
There are refrigerators on the ISS

**Comment by JLefebvre55** [comment]
**UPDATE**: Migrating away from manual pollination (re: no cross-contamination), solution overview should only mention air circulation pollination.
