### ISSUE TITLE
[FEATURE] - Germination and Planting Procedures

### ISSUE THREAD

**Issue by nchareunsouk** [OpenFormTech/PeaPod#77]
Deal with germination and early-stage plant growth.

### Context
Decide on a method and process for germinating plants. (How to get from seeds to plants.)

**Describe the solution you'd like**
Create one.

**Describe alternatives you've considered**
Big red cup.

**Additional context**
None.

**Comment by nchareunsouk** [comment]
@JLefebvre55 @narvcharv 

- Seeds are placed into a "scrap puck" (see #82).
- The puck is placed into a grow cup.
- Grow cup is inserted into a grow plate.
- Program is started in the dashboard.

**Comment by JLefebvre55** [comment]
Looks good - for now keep it general with a "clone collar" being made out of either plant waste or reusable neoprene. See #83
