### ISSUE TITLE
[DOCS] - Provide Examples of Crop Output Quality in Design Report

### ISSUE THREAD

**Issue by nchareunsouk** [OpenFormTech/PeaPod#78]
Provide examples of crop output quality throughout design report.
_Instead of just saying "peapod will grow soybeans" add examples of how the soybeans are better than normally grown soybeans._

Depending on the section, quantify why the peapod plants are better with areas such as nutrients or output quantity or inputs efficiency, etc... and compare to studies or reputable sources that cover conventionally grown counterparts. 

**Sections that apply:**
- Palatability of Outputs
- Inputs and Outputs
- Acceptability of Food Products
- any others that may apply

**Comment by JLefebvre55** [comment]
@narvcharv See what I wrote for the Output Quality subsection under Resource Inputs and Outputs

**Comment by narvcharv** [comment]
@JLefebvre55 Which branch is that on?

(I started working on this in docs-designreport-cropquality which I branched off of docs-designreport-performance, but it's missing Inputs/Outputs and Acceptability)

**Comment by JLefebvre55** [comment]
Done
