### ISSUE TITLE
[DOCS] - Solution Overview: Add Feature Subsections to Optimization

### ISSUE THREAD

**Issue by nchareunsouk** [OpenFormTech/PeaPod#79]
Elaborate on the features outlined in the Optimization section (data collection and surrogate modeling).

**Additional Notes:**
1. The issue on the innovation section - Open source is genuinely beneficial, it accelerates optimization.
2. The issue on safety of process/products - The nutrients and pH solutions never reach the crop outputs, it's all contained within the aeroponic chamber; washing the crops.

**Comment by JLefebvre55** [comment]
Unsure why this exists
