### ISSUE TITLE
Harvesting and Processing of Seeds

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#81]
Determine the process for the harvesting and processing of seeds for seed bank restoration.

Seed pre-storage process (i.e. dehydration, vacuum seal)?

NOTE: i think this might be trivial

**Comment by nchareunsouk** [comment]
@JLefebvre55 @narvcharv @JonasMarshall

- Plants that are set aside for seeds are not harvested until seeds have developed (some plants may still be eaten when seeds have formed.)
- If the plant has flowers, the seeds are removed from the flowers by hand.
- If the plant has fruits, the fruits are opened, the seeds are located and collected by hand.
- The seeds are dried.
- The seeds are vacuum sealed or stored in an air-tight container (such as a glass jar).
- Seeds are stored at a temperature between 32° and 41°F

**Comment by JLefebvre55** [comment]
Looks good. See #83
