### ISSUE TITLE
[BUG] - Documentation Continuity and Design Concept Completeness

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#90]
Ensure that all 3 major pieces of documentation (Design Report, Solution Overview, and Animation Script) have **no contradictions** and **all the same solution approaches, decisions, and features**.

In addition, make sure we captured our entire design (all concepts) in at least one place in the design report

- [x] Process specifics
  - [x] Setup
  - [x] Maintenance
  - [x] Pollination
  - [x] Planting
  - [x] Harvest
  - [x] Shutdown

**Comment by narvcharv** [comment]
[List of the "whats" of PeaPod and their inconsistencies between documents](https://docs.google.com/spreadsheets/d/1Ivw879PlWkdwKaojwuVll-PaNTMuXln3lt9_Ecp0N8I/edit?usp=sharing)

**Comment by JLefebvre55** [comment]
Fixed
